server:
    port: 8080
    error:
        path: /api/auth/error
spring:
    storePath: D:\rednoteUpload\images
    jackson:
        default-property-inclusion: NON_NULL
    servlet:
        multipart:
            enabled: true
            max-file-size: 15MB
            max-request-size: 50MB
            file-size-threshold: 10MB
            location: /tmp
    redis:
        expiration: 3600 #秒
        allowedOnlineNum: 5
        userTokenSetHeader: "user:token:"
        data:
            host: 127.0.0.1       # Redis 服务器地址
            port: 6379            # Redis 端口
            password:             # 如果有密码则填写
            database: 0           # 选择数据库 0-15
            timeout: 6000ms       # 连接超时
            lettuce:
            pool:
                max-active: 20    # 最大连接数
                max-wait: 1000ms  # 最大等待时间
                max-idle: 10      # 最大空闲连接
                min-idle: 5       # 最小空闲连接
    datasource:
        url: jdbc:postgresql://localhost:5432/rednote
        username: postgres 
        password: 3504554534
        driver-class-name: org.postgresql.Driver
        tomcat:
            max-wait: 10000
            max-active: 50
            max-idle: 25
            min-idle: 5
    jpa:
        hibernate: 
            dialect: org.hibernate.dialect.PostgreSQLDialect
            ddl-auto: update
        # show-sql: true
        properties:
            hibernate:
                format_sql: true
jwt:
    secret: bqK5v1EisVgkzGk4xUOkV0Q5nlf4X3Wg0ApnMduFwb8=
    expiration: 7200  #seconds
    header: Authorization
    prefix: Bearer 
    token-type: JWT
    issuer: rednote
    audience: rednote-user
    loginHeader: "login:user:"
    blackTokenHeader: "setex jwt:blacklist:"
role:
    separator: ":"

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
  info:
    title: 示例API
    description: 这是你的API说明
    version: v1.0
app:
    feed:
        inbox-max-size: 2000       # 每个用户收件箱最多保留多少条
        dedup-ttl-seconds: 172800  # 去重键2天过期
        stream-group: note-push    # 消费者组
        batch-size: 500            # 每批推送粉丝条数
        bigv-threshold: 500000     # 超大V阈值（粉丝数）
        stream:
            name: note-published
            batch-size: 10
            poll-timeout-seconds: 2
            consumers: 3
        reclaim:
            idle-seconds: 60              # Pending 消息超时多久才会被回收
            batch-size: 50              # 每次最多回收多少条
            consumer: reclaimer            # 回收消息的消费者名
            fixed-delay-ms: 300000         # 定时任务多久跑一次（10秒）
            max-claims: 3                      # 最多重试次数
        # retry:
        #     max-attempts: 3                  # 重试次数
        #     ttl-seconds: 3600                 # 重试计数键TTL